version: '3'

services:
  ubuntu:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./data:/app/data
    command: >
      sh -c "
        tail -f /dev/null
      "